<a href="https://colab.research.google.com/github/JoshuaCora1806/mi-lab01-cs/blob/develop/Laboratorio1_Cora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SEMANA 1 - INTRODUCCIÓN A LA MINERÍA DE DATOS
## Laboratorio 1
Alumno: Cora Salazar, Joshua Jian

Indicaciones:
*   El trabajo en su totalidad debe ser hecho en un notebook de ‘Jupyter’.
*   Cree una cabecera que lleve por título el tema de la semana y debajo de él coloque un ‘Markdown’ con su nombre y apellido.
*   Ejecute su notebook, grábelo, descárguelo como HTML y conviértalo a PDF. Suba el notebook y el PDF indique junto con el CSV que se obtuvo de Kaggle, en el apartado que el docente.

### ACTIVIDAD A
Lea cada base de datos y almacénela en un data frame indicando la cantidad de registros y atributos.

In [31]:
# Importar la libreria pandas
import pandas as pd

In [44]:
# Leer el csv
df = pd.read_csv('country_wise_latest.csv')
df.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa

In [45]:
# Obtener las dimensiones del dataframe
reg_atr = df.shape

# Imprimir la cantidad de registros y atributos
print(f'Cantidad de registros: {reg_atr[0]}')
print(f'Cantidad de atributos: {reg_atr[1]}')

Cantidad de registros: 187
Cantidad de atributos: 15

### ACTIVIDAD B
Determine la cantidad de variables numéricas y no numéricas. Además, indique si existen valores perdidos.

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    object
 1   Confirmed               187 non-null    int64
 2   Deaths                  187 non-null    int64
 3   Recovered               187 non-null    int64
 4   Active                  187 non-null    int64
 5   New cases               187 non-null    int64
 6   New deaths              187 non-null    int64
 7   New recovered           187 non-null    int64
 8   Deaths / 100 Cases      187 non-null    float64
 9   Recovered / 100 Cases   187 non-null    float64
 10  Deaths / 100 Recovered  187 non-null    float64
 11  Confirmed last week     187 non-null    int64
 12  1 week change           187 non-null    int64
 13  1 week % increase       187 non-null    float64
 14  WHO Region              187 non-null    object
dtypes: float64(4), int64(9), object(2)
memory usage: 22.0+ KB

In [51]:
# Contar var numericas
num_var = df.select_dtypes(include=['number']).shape[1]

# Contar var no numericas
nonum_var = df.select_dtypes(exclude=['number']).shape[1]

# Imprimir las cantidades
print(f"Cantidad de variables numéricas: {num_var}")
print(f"Cantidad de variables no numéricas: {nonum_var}")

Cantidad de variables numéricas: 13
Cantidad de variables no numéricas: 2

In [52]:
# Calcular la cantidad de nulos
nulos = df.isnull().sum().sum()

print(f"La cantidad de nulos en el dataframe: {nulos}")

La cantidad de nulos en el dataframe: 0

### ACIVIDAD C
Calcule estadísticos descriptivos para las variables numéricas (medidas de tendencia central, medidas de dispersión, valor máximo, valor mínimo, entre otras)

In [53]:
# Obtenemos los estadísticos descriptivos del dataframe
df.describe()

,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase
count,1.870000e+02,187.000000,1.870000e+02,1.870000e+02,187.000000,187.000000,187.000000,187.000000,187.000000,187.00,1.870000e+02,187.000000,187.000000
mean,8.813094e+04,3497.518717,5.063148e+04,3.400194e+04,1222.957219,28.957219,933.812834,3.019519,64.820535,inf,7.868248e+04,9448.459893,13.606203
std,3.833187e+05,14100.002482,1.901882e+05,2.133262e+05,5710.374790,120.037173,4197.719635,3.454302,26.287694,NaN,3.382737e+05,47491.127684,24.509838
min,1.000000e+01,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000e+01,-47.000000,-3.840000
25%,1.114000e+03,18.500000,6.265000e+02,1.415000e+02,4.000000,0.000000,0.000000,0.945000,48.770000,1.45,1.051500e+03,49.000000,2.775000
50%,5.059000e+03,108.000000,2.815000e+03,1.600000e+03,49.000000,1.000000,22.000000,2.150000,71.320000,3.62,5.020000e+03,432.000000,6.890000
75%,4.046050e+04,734.000000,2.260600e+04,9.149000e+03,419.500000,6.000000,221.000000,3.875000,86.885000,6.44,3.708050e+04,3172.000000,16.855000
max,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,56336.000000,1076.000000,33728.000000,28.560000,100.000000,inf,3.834677e+06,455582.000000,226.320000